sudo: false

language: node_js

node_js:
  - "8"

addons:
  firefox: "52.0"

cache:
  directories:
    - node_modules
env:
  - DISPLAY=:99.0

before_script:
  - "rm src/ol/renderer/webgl/*shader.js"
  - "sh -e /etc/init.d/xvfb start"
  - "npm ls || true"

script: "make ci"

branches:
  only:
    - master
